name: 'Install IPOPT (Octave)'
description: 'Build and install Octave interface for IPOPT'
author: 'Ray Zimmerman'

runs:
  using: "composite"
  steps:
    # expects that Octave and IPOPT libraries have already been installed
    - name: Build IPOPT Octave interface
      env:
        IPOPT_VER: 3.11.9
      run: |
        echo "IPOPT_PATH=$HOME/build/ipopt" >> $GITHUB_ENV
        [ ! -d $HOME/build ] && mkdir -p $HOME/build
        export PKG_CONFIG_PATH=$HOME/install/lib/pkgconfig
        curl -SL https://github.com/coin-or/Ipopt/archive/releases/${IPOPT_VER}.tar.gz | tar -xzC $HOME/build
        mv $HOME/build/Ipopt-releases-${IPOPT_VER}/Ipopt/contrib/MatlabInterface $HOME/build/ipopt
        mv ${{ github.action_path }}/ipopt/Makefile $HOME/build/ipopt/src
        make -C $HOME/build/ipopt/src
        mv $HOME/build/ipopt/src/*.mex $HOME/build/ipopt/
      shell: bash

    - name: Install IPOPT Octave interface
      run: $ML_CMD "addpath('${IPOPT_PATH}'); savepath"
      shell: bash

branding:
  icon: 'zap'
  color: 'yellow'
