name: 'Install IPOPT (Octave)'
description: 'Build and install Octave interface for IPOPT'
author: 'Ray Zimmerman'

inputs:
  cached:
    description: 'true means installing from a cached build'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    # expects that Octave and IPOPT libraries have already been installed
    - name: Build IPOPT Octave interface
      env:
        MEXIPOPT_BRANCH: no-bin
      run: |
        export IPOPT_PATH=$HOME/build/ipopt
        ${{ inputs.cached }} && echo "cached - skip build" || echo "Not cached - build it"
        ! ${{ inputs.cached }} && [ ! -d $HOME/build ] && mkdir -p $HOME/build
        ! ${{ inputs.cached }} && mkdir -p $HOME/build/ipopt
        ! ${{ inputs.cached }} && git clone -b ${MEXIPOPT_BRANCH} --depth=1 https://github.com/rdzman/mexIPOPT.git $HOME/build/mexIPOPT
        ! ${{ inputs.cached }} && cd $HOME/build/mexIPOPT/toolbox
        ! ${{ inputs.cached }} && export PKG_CONFIG_PATH=$HOME/install/lib/pkgconfig
        ! ${{ inputs.cached }} && [ ! -d $HOME/build/mexIPOPT/toolbox/bin ] && mkdir -p $HOME/build/mexIPOPT/toolbox/bin
        ! ${{ inputs.cached }} && octave-cli --no-gui --eval "CompileIpoptMexLib"
        ! ${{ inputs.cached }} && ls -al $HOME/build/mexIPOPT/toolbox/bin
        ! ${{ inputs.cached }} && mv $HOME/build/mexIPOPT/toolbox/lib/ipopt_auxdata.m $HOME/build/ipopt/
        ! ${{ inputs.cached }} && mv $HOME/build/mexIPOPT/toolbox/bin/ipopt_oct.mex $HOME/build/ipopt/ipopt.mex
        echo "IPOPT_PATH=${IPOPT_PATH}" >> $GITHUB_ENV
      shell: bash
#         ! ${{ inputs.cached }} && ls -al $HOME/build/mexIPOPT/toolbox/lib
#         ! ${{ inputs.cached }} && mkoctfile -p OCTINCLUDEDIR
#         ! ${{ inputs.cached }} && pkg-config --cflags ipopt
#         ! ${{ inputs.cached }} && pkg-config --libs ipopt

    - name: Install IPOPT Octave interface
      run: |
        echo "$ML_CMD \"addpath('${IPOPT_PATH}'); savepath\""
        $ML_CMD "addpath('${IPOPT_PATH}'); savepath"
      shell: bash

branding:
  icon: 'zap'
  color: 'yellow'
