name: CI

# controls when action will run
on:
  # triggers workflow on push events
  push:
  # allows workflow to be triggered manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest, macos-11, macos-12, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache IPOPT Libs (macOS)
      if: startsWith(matrix.os, 'macos')
      id: cache-ipopt-libs
      env:
        cache-name: ipopt-libs
      uses: actions/cache@v3
      with:
        path: ~/install
        key: ${{ matrix.os }}-${{ env.cache-name }}

    - name: Build IPOPT (macOS)
      if: startsWith(matrix.os, 'macos') && steps.cache-ipopt-libs.outputs.cache-hit != 'true'
      uses: MATPOWER/action-build-ipopt-macos@v1

    - name: Install Octave (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      uses: MATPOWER/action-install-octave-linux@v1
      with:
        ipopt-libs: true

    - name: Install Octave (macOS)
      if: startsWith(matrix.os, 'macos')
      uses: MATPOWER/action-install-octave-macos@v1

    - name: Octave ${{ env.ML_VER }} Installed
      run: $ML_CMD ver
    
    - name: Install IPOPT interface for Octave
      uses: ./.

    - name: Test IPOPT availability, print version number
      run:  |
        export IPOPT_TEST_PATH=${GITHUB_WORKSPACE}/.github/ipopt
        env $ML_PATHVAR=$IPOPT_TEST_PATH $ML_CMD "if ~have_feature_ipopt(), exit(1); end"
        env $ML_PATHVAR=$IPOPT_TEST_PATH $ML_CMD "if ~exist('ipopt_auxdata'), exit(1); end"
        env $ML_PATHVAR=$IPOPT_TEST_PATH $ML_CMD "qps_ipopt([],[1; 1],[1 1],[2],[2],[1; 1],[1; 1],[1; 1],struct('verbose', 2));"
        ls -al $IPOPT_PATH
